#*** -- DO NOT CHANGE THE app SECTION, ONLY FOR NEW ADDING *** -- #
app:
  storage:
    raw-csv-dir: F:/GT-v1-shared-storage/raw
    cleaned-csv-dir: F:\GT-v1-shared-storage\cleaned
    shared-root: F:\GT-v1-shared-storage
    sharedRoot: F:\\GT-v1-shared-storage
    rule-json-dir: F:\GT-v1-shared-storage\rules
    rule-output-dir: F:\GT-v1-shared-storage\rule-output
  api:
    raw-file: /api/v1/raw-file
    raw-data-clean: /api/v1/raw-file-clean
    cleaned-data-details: /api/v1/cleaned-data-details
    indicator:
      details: /api/v1/indicator
      run: /api/v1/indicator/run
    experiments:
      ema-macd: /api/v1/experiments/merge-td-ts/run
    rule:
      create: /api/v1/rule
      get-all: /api/v1/rule
      get-one: /api/v1/rule/get-one
      execute: /api/v1/rule/execute
      summary-generate: /api/v1/rule-summary/generate
      summary-get-one: /api/v1/rule-summary/get-one
      summary-get-all: /api/v1/rule-summary
  python:
    rule-executor-script: F:\GT-v1-engine\scripts\gt_rule_dynamic_csv_executor.py
    rule-td-only-executor-script: F:\GT-v1-engine\scripts\gt_rule_td_only_dynamic_csv_executor.py
    rule-summary-script: F:\GT-v1-engine\scripts\gt_rule_trade_csv_summary.py

firebase:
  bucket-name: gt-v1-f2880.firebasestorage.app
  service-account-path: file:F:/GT-v1-orchestrator/secrets/firebase-service-account.json
gt-v1:
  python:
    executable: python
    engine-root-path: F:/GT-v1-engine
    cleaned-root-path: F:/GT-v1-shared-storage/cleaned
    macd-script-relative-path: scripts/run_macd_td_ts_from_cleaned_csv.py
    output-dir: F:/GT-v1-shared-storage/indicators
    ema-stack-script-relative-path: scripts/run_ema_stack_td_ts_from_cleaned_csv.py
    ema-stack-output-dir: F:/GT-v1-shared-storage/indicators
    indicators-root-path: F:/GT-v1-shared-storage/indicators
    experiments-root-path: F:/GT-v1-shared-storage/experiments
    merge-td-ts-script-relative-path: scripts/merge_two_indicator_td_ts_csv.py
    timeout-seconds: 300

spring:
  application:
    name: GT-v1-orchestrator
  datasource:
    url: jdbc:mysql://localhost:3306/gt_v1_orchestrator
    username: root
    password: 1234
  data:
    mongodb:
      uri: mongodb://localhost:27017/gt_v1_orchestrator
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

server:
  port: 8080
