app:
  storage:
    raw-csv-dir: F:/GT-v1-shared-storage/raw
    sharedRoot: "F:\\GT-v1-shared-storage"
  api:
    raw-file: /api/v1/raw-file
    raw-data-clean: /api/v1/raw-file-clean

firebase:
#  bucket-name: gt-v1-f2880.firebasestorage.app
#  service-account-path: classpath:firebase/gt-v1-f2880-firebase-adminsdk-fbsvc-32f118650a.json
  bucket-name: ${FIREBASE_BUCKET_NAME}
  service-account-path: ${FIREBASE_SERVICE_ACCOUNT_PATH}

spring:
  application:
    name: GT-v1-orchestrator
  datasource:
    url: jdbc:mysql://localhost:3306/gt_v1_orchestrator
    username: root
#    password: 1234
    password: ${DB_PASSWORD}
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

server:
  port: 8080
